services:
  - type: web
    name: forex-trading-app
    env: docker
    plan: free
    branch: main
    healthCheckPath: /api/health
    envVars:
      - key: OANDA_API_KEY
        sync: false
      - key: OANDA_ACCOUNT_ID
        sync: false
      - key: OANDA_ENVIRONMENT
        value: practice
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False
      - key: PORT
        value: 5000
